import { StyleSheet } from "react-native";

export const formularioExperienciaStyle = StyleSheet.create({
  fondoOscuro: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "flex-end",
  },
  hoja: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    maxHeight: "85%",
  },
  titulo: {
    fontSize: 20,
    fontWeight: "700",
    color: "#123B63",
    marginBottom: 16,
  },
  etiqueta: {
    fontSize: 13,
    fontWeight: "600",
    color: "#4E6780",
    marginBottom: 6,
    marginTop: 12,
  },
  input: {
    borderWidth: 1,
    borderColor: "#D9DEE4",
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 15,
    color: "#2D3748",
    backgroundColor: "#FAFBFC",
  },
  inputMultilinea: {
    minHeight: 90,
    textAlignVertical: "top",
  },
filaCategorias: {
  flexDirection: "row",
  flexWrap: "wrap",
  justifyContent: "space-between",
},
chipCategoria: {
  width: "48%",
  borderWidth: 1.5,
  borderColor: "#D9DEE4",
  borderRadius: 12,
  paddingHorizontal: 12,
  paddingVertical: 10,
  marginBottom: 10,
  backgroundColor: "#FFFFFF",
  alignItems: "center",
  justifyContent: "center",
},
chipCategoriaActiva: {
  backgroundColor: "#123B63",
  borderColor: "#123B63",
},
chipCategoriaTexto: {
  fontSize: 13,
  fontWeight: "600",
  color: "#2D3748",
  textAlign: "center",
},
chipCategoriaTextoActivo: {
  fontSize: 13,
  fontWeight: "600",
  color: "#FFFFFF",
  textAlign: "center",
},
chipCategoriaContenido: {
  flexDirection: "row",
  alignItems: "center",
  justifyContent: "center",
},
chipCategoriaIcono: {
  marginRight: 6,
},

  // Tarjeta única de ubicación (tocable → abre el mapa)
  tarjetaUbicacion: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F0F6FC",
    borderWidth: 1.5,
    borderColor: "#C5D6E8",
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 12,
    marginTop: 4,
  },
  tarjetaUbicacionIcono: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
    borderWidth: 1,
    borderColor: "#D6E4F0",
  },
  tarjetaUbicacionTexto: {
    flex: 1,
  },
  tarjetaUbicacionCoords: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1D7A46",
    marginBottom: 2,
  },
  tarjetaUbicacionTitulo: {
    fontSize: 14,
    fontWeight: "700",
    color: "#123B63",
    marginBottom: 2,
  },
  tarjetaUbicacionHint: {
    fontSize: 12,
    color: "#8A99A8",
  },

  filaImagenes: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  miniaturaContenedor: {
    width: 80,
    height: 80,
    borderRadius: 10,
    overflow: "hidden",
  },
  miniatura: {
    width: "100%",
    height: "100%",
  },
  botonQuitarImagen: {
    position: "absolute",
    top: 2,
    right: 2,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "rgba(0,0,0,0.6)",
    alignItems: "center",
    justifyContent: "center",
  },
  botonQuitarImagenTexto: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "700",
  },
  botonAgregarImagen: {
    width: 80,
    height: 80,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: "#D9DEE4",
    borderStyle: "dashed",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FAFBFC",
  },
  botonAgregarImagenTexto: {
    fontSize: 12,
    color: "#123B63",
    fontWeight: "600",
  },
  filaBotones: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginTop: 24,
    marginBottom: 8,
    gap: 10,
  },
  botonCancelar: {
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 10,
  },
  botonCancelarTexto: {
    color: "#8A99A8",
    fontWeight: "600",
  },
  botonGuardar: {
    backgroundColor: "#123B63",
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 10,
    minWidth: 100,
    alignItems: "center",
  },
  botonGuardarDeshabilitado: {
    backgroundColor: "#B7C3CE",
  },
  botonGuardarTexto: {
    color: "#FFFFFF",
    fontWeight: "700",
  },
});